using System.Diagnostics;
using System.Text;
using System.Text.Json;
using SentribeeConsole.Web.Application.Contracts;
using SentribeeConsole.Web.Domain.Entities;

namespace SentribeeConsole.Web.Infrastructure.Runtime;

public sealed class LocalEdgeRuntimeService(
    IConfiguration configuration,
    IServerResourceService serverResourceService,
    ILogger<LocalEdgeRuntimeService> logger) : IEdgeRuntimeService
{
    private readonly string _runtimeRoot = configuration["EdgeRuntime:Root"] ?? "/opt/sentribee-edge-ai";
    private readonly string _sshUser = configuration["EdgeRuntime:SshUser"] ?? "ubuntu";
    private readonly string _sshKeyPath = configuration["EdgeRuntime:SshKeyPath"] ?? "/home/ubuntu/.ssh/id_ed25519";
    private readonly string _openAiApiKey = configuration["OpenAI:ApiKey"] ?? string.Empty;
    private readonly string _openAiModel = configuration["OpenAI:Model"] ?? "gpt-5.4-mini";
    private readonly string _openAiBaseUrl = configuration["OpenAI:BaseUrl"] ?? "https://api.openai.com/v1/";
    private static readonly HashSet<string> AutoGeneratedEnvironmentKeys = new(StringComparer.OrdinalIgnoreCase)
    {
        "SENTRIBEE_INSTANCE",
        "DEVICE_CODE",
        "DEVICE_ID",
        "CAMERA_ID",
        "RTSP_URL",
        "RTSP_FALLBACK_URL",
        "GATEWAY_MAC",
        "HLS_OUTPUT_DIR",
        "SENTRIBEE_CLIENT_NAME",
        "SENTRIBEE_DEVICE_ID",
        "SENTRIBEE_DEVICE_DB_ID",
        "SENTRIBEE_RTSP_URL",
        "SENTRIBEE_GATEWAY_MAC",
        "SENTRIBEE_INSTANCE_ENV",
        "SENTRIBEE_ENV_FILE"
    };
    private static readonly HashSet<string> ManagedHiddenEnvironmentKeys = new(StringComparer.OrdinalIgnoreCase)
    {
        "SENTRIBEE_CONSOLE_API_KEY",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "OPENAI_BASE_URL"
    };

    public async Task<EdgeRuntimeStartResult> StartAsync(EdgeDevice device, CancellationToken cancellationToken)
    {
        try
        {
            var resources = await serverResourceService.ListAsync(0, cancellationToken);
            var resource = resources.FirstOrDefault(item =>
                string.Equals(item.InstanceName, device.ServerResourceInstanceName, StringComparison.OrdinalIgnoreCase));
            if (resource is null)
            {
                return new EdgeRuntimeStartResult(
                    false,
                    $"Server resource {device.ServerResourceInstanceName ?? "Unbound"} was not found.");
            }

            var rtspUrl = ResolveRtspUrl(device);
            var gatewayMac = ResolveGatewayMac(device);
            var rtspFallbackUrl = ResolveRtspFallbackUrl(rtspUrl);
            var host = string.IsNullOrWhiteSpace(resource.PublicDomain)
                ? resource.PublicIpAddress
                : resource.PublicDomain;
            if (string.IsNullOrWhiteSpace(host))
            {
                return new EdgeRuntimeStartResult(false, "Selected server has no public domain or IP address.");
            }

            var script = BuildRemoteStartScript(device, rtspUrl, rtspFallbackUrl, gatewayMac);
            var startInfo = new ProcessStartInfo("ssh")
            {
                UseShellExecute = false,
                RedirectStandardInput = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true
            };
            startInfo.ArgumentList.Add("-i");
            startInfo.ArgumentList.Add(_sshKeyPath);
            startInfo.ArgumentList.Add("-o");
            startInfo.ArgumentList.Add("StrictHostKeyChecking=no");
            startInfo.ArgumentList.Add("-o");
            startInfo.ArgumentList.Add("BatchMode=yes");
            startInfo.ArgumentList.Add("-o");
            startInfo.ArgumentList.Add("ConnectTimeout=8");
            startInfo.ArgumentList.Add($"{_sshUser}@{host}");
            startInfo.ArgumentList.Add("bash");
            startInfo.ArgumentList.Add("-s");

            using var process = Process.Start(startInfo);
            if (process is null)
            {
                return new EdgeRuntimeStartResult(false, "Unable to start SSH process.");
            }

            await process.StandardInput.WriteAsync(script);
            await process.StandardInput.FlushAsync(cancellationToken);
            process.StandardInput.Close();
            var completed = await Task.Run(() => process.WaitForExit(15000), cancellationToken);
            if (!completed)
            {
                try
                {
                    process.Kill(entireProcessTree: true);
                }
                catch
                {
                    // Best-effort cleanup after SSH timeout.
                }

                return new EdgeRuntimeStartResult(false, $"Timed out connecting to {_sshUser}@{host}.");
            }

            var output = await process.StandardOutput.ReadToEndAsync(cancellationToken);
            var error = await process.StandardError.ReadToEndAsync(cancellationToken);
            if (process.ExitCode != 0)
            {
                var detail = string.IsNullOrWhiteSpace(error) ? output : error;
                return new EdgeRuntimeStartResult(false, detail.Trim());
            }

            logger.LogInformation(
                "Started remote Edge AI runtime for device {DeviceCode} on {Host}.",
                device.DeviceCode,
                host);
            return new EdgeRuntimeStartResult(
                true,
                string.IsNullOrWhiteSpace(output) ? $"Start command sent to {host}." : output.Trim());
        }
        catch (Exception exception)
        {
            logger.LogError(exception, "Unable to start Edge AI runtime for device {DeviceCode}.", device.DeviceCode);
            return new EdgeRuntimeStartResult(false, exception.Message);
        }
    }

    public async Task<IReadOnlyList<EdgeRuntimeEnvironmentVariable>> GetEditableEnvironmentAsync(
        EdgeDevice device,
        CancellationToken cancellationToken)
    {
        var runtimeContext = await ResolveRuntimeContextAsync(device, cancellationToken);
        if (!runtimeContext.Success)
        {
            throw new InvalidOperationException(runtimeContext.Message);
        }

        var script = BuildRemoteEnvironmentReadScript(device);
        var result = await RunRemoteScriptAsync(runtimeContext.Host, script, TimeSpan.FromSeconds(15), cancellationToken);
        if (!result.Success)
        {
            throw new InvalidOperationException(result.Message);
        }

        return JsonSerializer.Deserialize<List<EdgeRuntimeEnvironmentVariable>>(
                result.Message,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? [];
    }

    public async Task<EdgeRuntimeStartResult> SaveEditableEnvironmentAsync(
        EdgeDevice device,
        IReadOnlyDictionary<string, string> values,
        CancellationToken cancellationToken)
    {
        try
        {
            var runtimeContext = await ResolveRuntimeContextAsync(device, cancellationToken);
            if (!runtimeContext.Success)
            {
                return new EdgeRuntimeStartResult(false, runtimeContext.Message);
            }

            var cleaned = values
                .Where(item => IsEditableEnvironmentKey(item.Key))
                .ToDictionary(item => item.Key, item => item.Value ?? string.Empty, StringComparer.OrdinalIgnoreCase);
            var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(cleaned)));
            var script = BuildRemoteEnvironmentSaveScript(device, payload);
            return await RunRemoteScriptAsync(runtimeContext.Host, script, TimeSpan.FromSeconds(15), cancellationToken);
        }
        catch (Exception exception)
        {
            logger.LogError(exception, "Unable to save Edge AI runtime environment for device {DeviceCode}.", device.DeviceCode);
            return new EdgeRuntimeStartResult(false, exception.Message);
        }
    }

    private static string? ResolveRtspUrl(EdgeDevice device)
    {
        return device.Endpoints
            .Select(endpoint => endpoint.AccessUrl)
            .FirstOrDefault(url => url.StartsWith("rtsp://", StringComparison.OrdinalIgnoreCase));
    }

    private static string? ResolveGatewayMac(EdgeDevice device)
    {
        return device.Endpoints
            .Where(endpoint =>
                endpoint.DeviceName.Contains("gateway", StringComparison.OrdinalIgnoreCase) ||
                endpoint.DeviceName.Contains("ble", StringComparison.OrdinalIgnoreCase) ||
                endpoint.DeviceName.Contains("bluetooth", StringComparison.OrdinalIgnoreCase) ||
                endpoint.DeviceName.Contains("mac", StringComparison.OrdinalIgnoreCase) ||
                endpoint.AccessUrl.Contains(":", StringComparison.Ordinal))
            .Select(endpoint => endpoint.AccessUrl)
            .FirstOrDefault(value => !value.StartsWith("rtsp://", StringComparison.OrdinalIgnoreCase));
    }

    private static string ResolveRtspFallbackUrl(string? rtspUrl)
    {
        if (string.IsNullOrWhiteSpace(rtspUrl))
        {
            return string.Empty;
        }

        if (rtspUrl.Contains("stream1", StringComparison.OrdinalIgnoreCase))
        {
            return rtspUrl.Replace("stream1", "stream2", StringComparison.OrdinalIgnoreCase);
        }

        return rtspUrl;
    }

    private async Task<(bool Success, string Host, string Message)> ResolveRuntimeContextAsync(
        EdgeDevice device,
        CancellationToken cancellationToken)
    {
        var resources = await serverResourceService.ListAsync(0, cancellationToken);
        var resource = resources.FirstOrDefault(item =>
            string.Equals(item.InstanceName, device.ServerResourceInstanceName, StringComparison.OrdinalIgnoreCase));
        if (resource is null)
        {
            return (false, string.Empty, $"Server resource {device.ServerResourceInstanceName ?? "Unbound"} was not found.");
        }

        var host = string.IsNullOrWhiteSpace(resource.PublicDomain)
            ? resource.PublicIpAddress
            : resource.PublicDomain;
        return string.IsNullOrWhiteSpace(host)
            ? (false, string.Empty, "Selected server has no public domain or IP address.")
            : (true, host, string.Empty);
    }

    private async Task<EdgeRuntimeStartResult> RunRemoteScriptAsync(
        string host,
        string script,
        TimeSpan timeout,
        CancellationToken cancellationToken)
    {
        var startInfo = new ProcessStartInfo("ssh")
        {
            UseShellExecute = false,
            RedirectStandardInput = true,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true,
            StandardOutputEncoding = Encoding.UTF8,
            StandardErrorEncoding = Encoding.UTF8
        };
        startInfo.ArgumentList.Add("-i");
        startInfo.ArgumentList.Add(_sshKeyPath);
        startInfo.ArgumentList.Add("-o");
        startInfo.ArgumentList.Add("StrictHostKeyChecking=no");
        startInfo.ArgumentList.Add("-o");
        startInfo.ArgumentList.Add("BatchMode=yes");
        startInfo.ArgumentList.Add("-o");
        startInfo.ArgumentList.Add("ConnectTimeout=8");
        startInfo.ArgumentList.Add($"{_sshUser}@{host}");
        startInfo.ArgumentList.Add("bash");
        startInfo.ArgumentList.Add("-s");

        using var process = Process.Start(startInfo);
        if (process is null)
        {
            return new EdgeRuntimeStartResult(false, "Unable to start SSH process.");
        }

        await process.StandardInput.WriteAsync(script);
        await process.StandardInput.FlushAsync(cancellationToken);
        process.StandardInput.Close();
        var completed = await Task.Run(() => process.WaitForExit((int)timeout.TotalMilliseconds), cancellationToken);
        if (!completed)
        {
            try
            {
                process.Kill(entireProcessTree: true);
            }
            catch
            {
                // Best-effort cleanup after SSH timeout.
            }

            return new EdgeRuntimeStartResult(false, $"Timed out connecting to {_sshUser}@{host}.");
        }

        var output = await process.StandardOutput.ReadToEndAsync(cancellationToken);
        var error = await process.StandardError.ReadToEndAsync(cancellationToken);
        if (process.ExitCode != 0)
        {
            var detail = string.IsNullOrWhiteSpace(error) ? output : error;
            return new EdgeRuntimeStartResult(false, detail.Trim());
        }

        return new EdgeRuntimeStartResult(true, output.Trim());
    }

    private string BuildRemoteEnvironmentReadScript(EdgeDevice device)
    {
        return BuildRemoteEnvironmentBootstrap(device) + $$"""
            python3 - "$env_file" "$template_file" <<'PY'
            import json
            import sys

            env_file, template_file = sys.argv[1:3]
            auto_keys = {
                "SENTRIBEE_INSTANCE", "DEVICE_CODE", "DEVICE_ID", "CAMERA_ID", "RTSP_URL",
                "RTSP_FALLBACK_URL", "GATEWAY_MAC", "HLS_OUTPUT_DIR", "SENTRIBEE_CLIENT_NAME",
                "SENTRIBEE_DEVICE_ID", "SENTRIBEE_DEVICE_DB_ID", "SENTRIBEE_RTSP_URL",
                "SENTRIBEE_GATEWAY_MAC", "SENTRIBEE_INSTANCE_ENV", "SENTRIBEE_ENV_FILE"
            }
            managed_hidden_keys = {
                "SENTRIBEE_CONSOLE_API_KEY", "OPENAI_API_KEY", "OPENAI_MODEL", "OPENAI_BASE_URL"
            }

            def is_editable(key):
                return key not in auto_keys and key not in managed_hidden_keys and not key.upper().startswith("OPENAI_")

            def parse(path):
                values = {}
                order = []
                try:
                    lines = open(path, "r", encoding="utf-8").read().splitlines()
                except OSError:
                    return values, order
                for line in lines:
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#") or "=" not in line:
                        continue
                    key, value = line.split("=", 1)
                    key = key.strip()
                    if key and key not in values:
                        order.append(key)
                    values[key] = value
                return values, order

            template_values, template_order = parse(template_file)
            env_values, env_order = parse(env_file)
            keys = []
            for key in template_order + env_order:
                if is_editable(key) and key not in keys:
                    keys.append(key)

            def is_secret(key):
                upper = key.upper()
                return any(token in upper for token in ("KEY", "SECRET", "TOKEN", "PASSWORD", "PWD", "CREDENTIAL"))

            rows = []
            for key in keys:
                rows.append({
                    "name": key,
                    "value": env_values.get(key, template_values.get(key, "")),
                    "isSecret": is_secret(key),
                    "source": "current" if key in env_values else "template"
                })
            print(json.dumps(rows, ensure_ascii=False))
            PY
            """;
    }

    private string BuildRemoteEnvironmentSaveScript(EdgeDevice device, string base64Payload)
    {
        return BuildRemoteEnvironmentBootstrap(device) + $$"""
            values_payload={{ShellQuote(base64Payload)}}
            python3 - "$env_file" "$template_file" "$values_payload" <<'PY'
            import base64
            import json
            import sys

            env_file, template_file, values_payload = sys.argv[1:4]
            submitted = json.loads(base64.b64decode(values_payload).decode("utf-8"))
            auto_keys = {
                "SENTRIBEE_INSTANCE", "DEVICE_CODE", "DEVICE_ID", "CAMERA_ID", "RTSP_URL",
                "RTSP_FALLBACK_URL", "GATEWAY_MAC", "HLS_OUTPUT_DIR", "SENTRIBEE_CLIENT_NAME",
                "SENTRIBEE_DEVICE_ID", "SENTRIBEE_DEVICE_DB_ID", "SENTRIBEE_RTSP_URL",
                "SENTRIBEE_GATEWAY_MAC", "SENTRIBEE_INSTANCE_ENV", "SENTRIBEE_ENV_FILE"
            }
            managed_hidden_keys = {
                "SENTRIBEE_CONSOLE_API_KEY", "OPENAI_API_KEY", "OPENAI_MODEL", "OPENAI_BASE_URL"
            }

            def is_editable(key):
                return key not in auto_keys and key not in managed_hidden_keys and not key.upper().startswith("OPENAI_")

            def template_keys(path):
                keys = []
                try:
                    lines = open(path, "r", encoding="utf-8").read().splitlines()
                except OSError:
                    return keys
                for line in lines:
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#") or "=" not in line:
                        continue
                    key = line.split("=", 1)[0].strip()
                    if key and key not in keys:
                        keys.append(key)
                return keys

            allowed = set(k for k in template_keys(template_file) if is_editable(k))
            allowed.update(k for k in submitted.keys() if is_editable(k))
            try:
                lines = open(env_file, "r", encoding="utf-8").read().splitlines()
            except OSError:
                lines = []
            output = []
            seen = set()
            for line in lines:
                key = line.split("=", 1)[0].strip() if "=" in line else None
                if key in allowed and key in submitted:
                    output.append(f"{key}={submitted[key]}")
                    seen.add(key)
                else:
                    output.append(line)
            if output and output[-1].strip():
                output.append("")
            for key in template_keys(template_file):
                if key in allowed and key in submitted and key not in seen:
                    output.append(f"{key}={submitted[key]}")
                    seen.add(key)
            for key, value in submitted.items():
                if key in allowed and key not in seen:
                    output.append(f"{key}={value}")
            open(env_file, "w", encoding="utf-8").write("\n".join(output).rstrip() + "\n")
            print(f"Environment saved to {env_file}.")
            PY
            """;
    }

    private string BuildRemoteEnvironmentBootstrap(EdgeDevice device)
    {
        var rtspUrl = ResolveRtspUrl(device);
        var gatewayMac = ResolveGatewayMac(device);
        var rtspFallbackUrl = ResolveRtspFallbackUrl(rtspUrl);
        return $$"""
            set -e
            root={{ShellQuote(_runtimeRoot)}}
            device_code={{ShellQuote(device.DeviceCode)}}
            device_db_id={{ShellQuote(device.Id.ToString())}}
            rtsp_url={{ShellQuote(rtspUrl ?? string.Empty)}}
            rtsp_fallback_url={{ShellQuote(rtspFallbackUrl)}}
            gateway_mac={{ShellQuote(gatewayMac ?? string.Empty)}}
            managed_openai_api_key={{ShellQuote(_openAiApiKey)}}
            managed_openai_model={{ShellQuote(_openAiModel)}}
            managed_openai_base_url={{ShellQuote(_openAiBaseUrl)}}
            managed_openai_api_key={{ShellQuote(_openAiApiKey)}}
            managed_openai_model={{ShellQuote(_openAiModel)}}
            managed_openai_base_url={{ShellQuote(_openAiBaseUrl)}}

            main_path="$root/main.py"
            if [ ! -f "$main_path" ]; then
              main_path="$root/main/main.py"
            fi
            if [ ! -f "$main_path" ]; then
              echo "Edge AI runtime main.py was not found under $root on $(hostname)." >&2
              exit 20
            fi

            main_dir="$(dirname "$main_path")"
            instance_dir="$root/instances/$device_code"
            env_file="$instance_dir/.env"
            template_file="$main_dir/.env.example"
            if [ ! -f "$template_file" ] && [ -f "$root/.env.example" ]; then
              template_file="$root/.env.example"
            fi
            mkdir -p "$instance_dir"
            if [ ! -f "$env_file" ]; then
              if [ -f "$template_file" ]; then
                cp "$template_file" "$env_file"
              else
                touch "$env_file"
              fi
            fi

            python3 - "$env_file" "$device_code" "$device_db_id" "$rtsp_url" "$rtsp_fallback_url" "$gateway_mac" "$managed_openai_api_key" "$managed_openai_model" "$managed_openai_base_url" <<'PY'
            import sys
            path, device_code, device_db_id, rtsp_url, rtsp_fallback_url, gateway_mac, openai_api_key, openai_model, openai_base_url = sys.argv[1:10]
            values = {
                "SENTRIBEE_INSTANCE": device_code,
                "DEVICE_CODE": device_code,
                "DEVICE_ID": device_code,
                "CAMERA_ID": device_code,
                "RTSP_URL": rtsp_url,
                "RTSP_FALLBACK_URL": rtsp_fallback_url,
                "GATEWAY_MAC": gateway_mac,
                "HLS_OUTPUT_DIR": f"instances/{device_code}/video",
                "SENTRIBEE_CLIENT_NAME": f"{device_code}-edge-ai-client",
                "SENTRIBEE_DEVICE_ID": device_code,
                "SENTRIBEE_DEVICE_DB_ID": device_db_id,
                "SENTRIBEE_RTSP_URL": rtsp_url,
                "SENTRIBEE_GATEWAY_MAC": gateway_mac,
                "OPENAI_API_KEY": openai_api_key,
                "OPENAI_MODEL": openai_model,
                "OPENAI_BASE_URL": openai_base_url,
            }
            try:
                lines = open(path, "r", encoding="utf-8").read().splitlines()
            except FileNotFoundError:
                lines = []
            output = []
            seen = set()
            for line in lines:
                key = line.split("=", 1)[0] if "=" in line else None
                if key in values:
                    output.append(f"{key}={values[key]}")
                    seen.add(key)
                else:
                    output.append(line)
            if output and output[-1].strip():
                output.append("")
            for key, value in values.items():
                if key not in seen:
                    output.append(f"{key}={value}")
            open(path, "w", encoding="utf-8").write("\n".join(output).rstrip() + "\n")
            PY

            """;
    }

    private string BuildRemoteStartScript(EdgeDevice device, string? rtspUrl, string rtspFallbackUrl, string? gatewayMac)
    {
        return $$"""
            set -e
            root={{ShellQuote(_runtimeRoot)}}
            device_code={{ShellQuote(device.DeviceCode)}}
            device_db_id={{ShellQuote(device.Id.ToString())}}
            rtsp_url={{ShellQuote(rtspUrl ?? string.Empty)}}
            rtsp_fallback_url={{ShellQuote(rtspFallbackUrl)}}
            gateway_mac={{ShellQuote(gatewayMac ?? string.Empty)}}
            managed_openai_api_key={{ShellQuote(_openAiApiKey)}}
            managed_openai_model={{ShellQuote(_openAiModel)}}
            managed_openai_base_url={{ShellQuote(_openAiBaseUrl)}}

            main_path="$root/main.py"
            if [ ! -f "$main_path" ]; then
              main_path="$root/main/main.py"
            fi
            if [ ! -f "$main_path" ]; then
              echo "Edge AI runtime main.py was not found under $root on $(hostname)." >&2
              exit 20
            fi

            main_dir="$(dirname "$main_path")"
            instance_dir="$root/instances/$device_code"
            env_file="$instance_dir/.env"
            mkdir -p "$instance_dir"

            if [ ! -f "$env_file" ]; then
              if [ -f "$main_dir/.env.example" ]; then
                cp "$main_dir/.env.example" "$env_file"
              elif [ -f "$root/.env.example" ]; then
                cp "$root/.env.example" "$env_file"
              else
                touch "$env_file"
              fi
            fi

            python3 - "$env_file" "$device_code" "$device_db_id" "$rtsp_url" "$rtsp_fallback_url" "$gateway_mac" "$managed_openai_api_key" "$managed_openai_model" "$managed_openai_base_url" <<'PY'
            import sys
            path, device_code, device_db_id, rtsp_url, rtsp_fallback_url, gateway_mac, openai_api_key, openai_model, openai_base_url = sys.argv[1:10]
            template_paths = []
            try:
                import os
                root = os.path.dirname(os.path.dirname(os.path.dirname(path)))
                main_dir = os.path.dirname(os.path.join(root, "main.py"))
                template_paths = [
                    path,
                    os.path.join(root, ".env.example"),
                    os.path.join(main_dir, ".env.example"),
                ]
            except Exception:
                template_paths = [path]

            def read_env_values(paths):
                result = {}
                for env_path in paths:
                    try:
                        source_lines = open(env_path, "r", encoding="utf-8").read().splitlines()
                    except OSError:
                        continue
                    for source_line in source_lines:
                        if not source_line or source_line.lstrip().startswith("#") or "=" not in source_line:
                            continue
                        key, value = source_line.split("=", 1)
                        if key not in result or (not result[key] and value):
                            result[key] = value
                return result

            inherited = read_env_values(template_paths)
            values = {
                "SENTRIBEE_INSTANCE": device_code,
                "DEVICE_CODE": device_code,
                "DEVICE_ID": device_code,
                "CAMERA_ID": device_code,
                "RTSP_URL": rtsp_url,
                "RTSP_FALLBACK_URL": rtsp_fallback_url,
                "GATEWAY_MAC": gateway_mac,
                "HLS_OUTPUT_DIR": f"instances/{device_code}/video",
                "SENTRIBEE_CLIENT_NAME": f"{device_code}-edge-ai-client",
                "SENTRIBEE_DEVICE_ID": device_code,
                "SENTRIBEE_DEVICE_DB_ID": device_db_id,
                "SENTRIBEE_RTSP_URL": rtsp_url,
                "SENTRIBEE_GATEWAY_MAC": gateway_mac,
                "SENTRIBEE_CONSOLE_URL": inherited.get("SENTRIBEE_CONSOLE_URL", "https://console.sentribee.ai"),
                "SENTRIBEE_CONSOLE_API_KEY": inherited.get("SENTRIBEE_CONSOLE_API_KEY", ""),
                "SENTRIBEE_EDGE_AUTH_PATH": inherited.get("SENTRIBEE_EDGE_AUTH_PATH", "/api/edge/auth"),
                "SENTRIBEE_EDGE_HEARTBEAT_PATH": inherited.get("SENTRIBEE_EDGE_HEARTBEAT_PATH", "/api/edge/heartbeat"),
                "SENTRIBEE_EDGE_EVENTS_PATH": inherited.get("SENTRIBEE_EDGE_EVENTS_PATH", "/api/edge/events"),
                "SENTRIBEE_HEARTBEAT_INTERVAL": inherited.get("SENTRIBEE_HEARTBEAT_INTERVAL", "30"),
                "OPENAI_API_KEY": openai_api_key,
                "OPENAI_MODEL": openai_model,
                "OPENAI_BASE_URL": openai_base_url,
            }
            try:
                lines = open(path, "r", encoding="utf-8").read().splitlines()
            except FileNotFoundError:
                lines = []
            seen = set()
            output = []
            for line in lines:
                key = line.split("=", 1)[0] if "=" in line else None
                if key in values:
                    output.append(f"{key}={values[key]}")
                    seen.add(key)
                else:
                    output.append(line)
            if output and output[-1].strip():
                output.append("")
            for key, value in values.items():
                if key not in seen:
                    output.append(f"{key}={value}")
            open(path, "w", encoding="utf-8").write("\n".join(output).rstrip() + "\n")
            PY

            old_pids="$(python3 - "$device_code" <<'PY'
            import os
            import sys

            device_code = sys.argv[1]
            current_pid = os.getpid()
            matches = []
            for name in os.listdir("/proc"):
                if not name.isdigit():
                    continue

                pid = int(name)
                if pid == current_pid:
                    continue

                try:
                    cmdline = open(f"/proc/{pid}/cmdline", "rb").read().replace(b"\0", b" ").decode("utf-8", "ignore")
                    environ = open(f"/proc/{pid}/environ", "rb").read().replace(b"\0", b"\n").decode("utf-8", "ignore")
                except OSError:
                    continue

                if "main.py" not in cmdline:
                    continue

                if f"SENTRIBEE_INSTANCE={device_code}" in environ or device_code in cmdline:
                    matches.append(str(pid))

            print(" ".join(matches))
            PY
            )"
            if [ -n "$old_pids" ]; then
              echo "Stopping previous runtime processes for $device_code: $old_pids" >> "$instance_dir/runtime.log"
              kill $old_pids 2>/dev/null || true
              sleep 1
              kill -9 $old_pids 2>/dev/null || true
            fi

            cd "$main_dir"
            python_bin="$root/venv/bin/python"
            if [ ! -x "$python_bin" ]; then
              python_bin="$root/.venv/bin/python"
            fi
            if [ ! -x "$python_bin" ]; then
              python_bin="$(command -v python3)"
            fi
            if [ -z "$python_bin" ] || [ ! -x "$python_bin" ]; then
              echo "No Python runtime found. Expected $root/venv/bin/python, $root/.venv/bin/python, or python3." >&2
              exit 21
            fi

            {
              echo "Starting at $(date -Is)"
              echo "Device: $device_code"
              echo "Main: $main_path"
              echo "Env: $env_file"
              echo "Python: $python_bin"
            } >> "$instance_dir/runtime.log"
            nohup env SENTRIBEE_INSTANCE="$device_code" SENTRIBEE_INSTANCE_ENV="$env_file" SENTRIBEE_ENV_FILE="$env_file" OPENAI_API_KEY="$managed_openai_api_key" OPENAI_MODEL="$managed_openai_model" OPENAI_BASE_URL="$managed_openai_base_url" "$python_bin" "$main_path" >> "$instance_dir/runtime.log" 2>&1 &
            echo "Start command sent to $(hostname) for $device_code using $python_bin."
            """;
    }

    private static string ShellQuote(string value)
    {
        return $"'{value.Replace("'", "'\"'\"'", StringComparison.Ordinal)}'";
    }

    private static bool IsEditableEnvironmentKey(string key)
    {
        return !AutoGeneratedEnvironmentKeys.Contains(key) &&
            !ManagedHiddenEnvironmentKeys.Contains(key) &&
            !key.StartsWith("OPENAI_", StringComparison.OrdinalIgnoreCase);
    }
}
