CREATE TABLE IF NOT EXISTS bee_FarmerSurveyResponse (
    id BIGINT NOT NULL AUTO_INCREMENT,
    ResponseGuid CHAR(36) NOT NULL,
    SurveyVersion VARCHAR(40) NOT NULL,
    SubmittedAtUtc DATETIME(6) NOT NULL,
    FarmName VARCHAR(180) NULL,
    FarmRole VARCHAR(120) NOT NULL,
    Region VARCHAR(120) NOT NULL,
    LivestockOperation VARCHAR(140) NOT NULL,
    CattleCount VARCHAR(60) NOT NULL,
    SheepCount VARCHAR(60) NOT NULL,
    FarmArea VARCHAR(60) NOT NULL,
    StaffCount VARCHAR(60) NOT NULL,
    ContactName VARCHAR(160) NULL,
    ContactPhone VARCHAR(80) NULL,
    ContactEmail VARCHAR(180) NULL,
    AnswerJson JSON NOT NULL,
    UserAgent VARCHAR(500) NULL,
    ReportTo VARCHAR(180) NOT NULL,
    ReportCc VARCHAR(180) NOT NULL,
    ReportStatus VARCHAR(30) NOT NULL DEFAULT 'Pending',
    ReportProvider VARCHAR(40) NULL,
    ReportProviderMessageId VARCHAR(200) NULL,
    ReportErrorText VARCHAR(1000) NULL,
    ReportSentAtUtc DATETIME(6) NULL,
    CreatedAtUtc DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    PRIMARY KEY (id),
    UNIQUE KEY UX_bee_FarmerSurveyResponse_Guid (ResponseGuid),
    KEY IX_bee_FarmerSurveyResponse_Submitted (SubmittedAtUtc),
    KEY IX_bee_FarmerSurveyResponse_ReportStatus (ReportStatus, SubmittedAtUtc),
    KEY IX_bee_FarmerSurveyResponse_Region (Region, SubmittedAtUtc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
