CREATE TABLE IF NOT EXISTS bee_WeComKfSync (
  CorpId VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  OpenKfId VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  NotifyToken VARCHAR(128) NOT NULL,
  TokenReceivedAtUtc DATETIME(6) NOT NULL,
  RequestedVersion BIGINT NOT NULL DEFAULT 1,
  CompletedVersion BIGINT NOT NULL DEFAULT 0,
  CursorValue VARCHAR(128) NOT NULL DEFAULT '',
  LastSuccessAtUtc DATETIME(6) NULL,
  LastError VARCHAR(80) NULL,
  NextAttemptAtUtc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (CorpId, OpenKfId)
) ENGINE=InnoDB;
